version: 1.0

environments:
  coder:
    files:
      - name: 'project files'
        include:
          - './packages/browser-utils/tsconfig.*.json'
          - './packages/browser-utils/vite.config.ts'
          - './packages/browser-utils/package.json'
          - './packages/browser-utils/project.json'
          -
          - './packages/responsive/tsconfig.*.json'
          - './packages/responsive/vite.config.ts'
          - './packages/responsive/package.json'
          - './packages/responsive/project.json'
          - './tsconfig.base.json'
          -
          - './*.(js|html|css|ts|scss)'

        instructions: |
          These are all project files. You can edit them as you like.
