name: Publish Tags

on:
  push:
    tags:
      - '*@*.*.*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          scope: '@trunkjs'
      - run: npm install
      - run: npm ci
      # - run: npx playwright install --with-deps chromium
      - run: npx nx report
      - name: Extract tagged package
        id: pkg
        shell: bash
        run: echo "name=${GITHUB_REF_NAME%@*}" >> "$GITHUB_OUTPUT"

      - run: npx nx run-many -p ${{ steps.pkg.outputs.name }} -t test build
      - run: npx nx release publish --access public -p ${{ steps.pkg.outputs.name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
