version: 1.0

environments:
  coder:
    files:
      - name: 'project files'
        include:
          - './**/*.(json|yml|ts)'
          - './demo/*/*.(json|yml|ts)'
          - './*.(js|html|css|ts|scss|json)'

        instructions: |
          These are all project files. You can edit them as you like.
